import Navigation from "~/app/components/Navigation";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-10`}>
        <h1 className="text-xl font-bold">Next.js 13.4</h1>
        <p className="text-gray-600">Exploring app router stable release.</p>
        <Navigation />

        <div className="py-4">{children}</div>
      </body>
    </html>
  );
}
